### ISSUE TITLE
AsyncWebServer + Teensy 4.1 + WiFININA instead of Ethernet?

### ISSUE THREAD

**Issue by JackBlair87** [khoih-prog/AsyncWebServer_Teensy41#1]
Hi! Would it be possible to modify this library to work with an ESP32 Coprocessor running on WiFiNINA? I am able to find the general WiFi library for WiFiNINA without Async capabilities (https://github.com/khoih-prog/WiFiWebServer), as well as this current Async library without WifiNINA, but not both together. Thanks for your help!

**Comment by khoih-prog** [comment]
Hi,

Thanks for your interest in the library. I'm sorry to say that it can be **quite some time** to provide Async support to **WiFiNINA**-related libraries because the WiFiNINA library is not **LwIP-based**.

Currently, only LwIP-based libraries, such as **QNEthernet, STM32Ethernet, Portenta_H7 Ethernet/WiFi, ESP32/ESP8266 WiFi, WT32_ETH01 (ESP32-based LAN8720 Ethernet)** can have Async support now.

I suggest you move to [**Portenta_H7 Async WiFi**](https://github.com/khoih-prog/Portenta_H7_AsyncWebServer) or ESP32 to have **current** Async support.

I don't know and hope somebody is willing and have time to convert the remaining sync Ethernet/WiFi libraries to support Async in the near future,

I have to close this issue now as I don't have plan to do so, at least for the near future, even I prefer Async.

Good Luck,
